#!/bin/bash


# Runs the tree simulation with the parameters in the control file
../treeSim/./HIV_treeSim -c pt7.ctrl

# Runs the dna simulation for the tree generated by the tree simulator. 
# The sequence at the root is given in the fasta file.
../dnaSim/./dna_sim -u 0.0000356 -a 0.4294 -i K03455_C1V2.fasta -s 1 -t SampledTree.txt -l LatentStates.txt -o example -f 0.35322:0.17636:0.21123:0.25919-1.0:6.9801:1.0:1.0:6.9801:1.0 -r
